package FixIt::Consts;

use constant {
    USER_LEVEL_BASE => 1,
    USER_LEVEL_LEAD => 2,
    USER_LEVEL_BRONZE => 3,
    USER_LEVEL_SILVER => 4,
    USER_LEVEL_GOLD => 5,
    USER_LEVEL_PLATINUM => 6,
    USER_ROLE_ADMIN => 1,
    USER_ROLE_BASIC => 2,
    EVENT_STATUS_NEW => 1,
    EVENT_STATUS_CONFIRMED => 2,
    EVENT_STATUS_PENDING_MONEY => 3,
    EVENT_STATUS_IN_PROGRESS => 4,
    EVENT_STATUS_FAILED => 5,
    EVENT_STATUS_FINISHED => 6,
    EVENT_TYPES_BASIC => 1,
    EVENT_TYPES_INTERMEDIATE => 2,
    EVENT_TYPES_ADVANCED => 3,
    EVENT_TYPES_ISTITUTION => 4,
    USER_EVENT_ROLES_WORKER => 1,
    USER_EVENT_ROLES_MANAGER => 2,
    USER_ACTION_TYPES_FIX => 1,
    USER_ACTION_TYPES_REPORTS => 2,
    USER_ACTION_TYPES_MONTH => 3,
    USER_ACHIVEMENTS_FIRST_REPORT => 1,
    USER_ACHIVEMENTS_FIRST_FIX => 2,
    USER_ACHIVEMENTS_REPORTS => 3,
    USER_ACHIVEMENTS_FIXES => 4,
    USER_ACHIVEMENTS_1_MONTH => 5,
    USER_ACHIVEMENTS_1_YEAR => 6
};

1;
